#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f '4-to_infinity_and_beyond')

# Check if the process is running and then kill it
if [ -n "$pid" ]; then
    kill "$pid"
    echo "Process terminated"
else
    echo "Process not found"
fi

