#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Check if the process is running and then kill it
if [ -n "$pid" ]
then
    kill "$pid"
    echo "Process terminated"
fi

