#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely with a 2-second sleep between each iteration.
# It also prints 'I am invincible!!!' when receiving a SIGTERM signal.

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "To infinity and beyond"
    sleep 2
done

