#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data.

awk '{count[$1" "$9]++} END {for (ip_code in count) print count[ip_code], ip_code}' apache-access.log | sort -nr

