#!/usr/bin/env bash
# Purpose: Configure localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
#Change your home IP
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
